# Condition with "when:"
- name:
  hosts: all
  tasks: 
  - name: Install NGINX on Devian
    apt: 
      name: nginx
      state: present
    when: ansible_os_family == "Debian" and
          ansible_distribution_version == "16.04"

  - name: 
    yum: 
        name: nginx
        state: present
    when: ansible_os_family == "RedHat" or
          ansible_os_family == "SUSE"


# Loop
- name: Intall Software
  hosts: all
  vars:
    packages: 
        - name: nginx
          required: True
        - name: mysql
          required: True
        - name: apache
          required: False
  tasks: 
  - name: Install "{{item.name}}" on Debian 
    apt: 
        name: "{{item.name}}"
        state: present 
    when: item.required == True
    Loop: "{{packages}}"